//! Crate generation (Cargo.toml and lib.rs)

use crate::parser::{IntentConfig, IntentStore};

/// Generate Cargo.toml content
pub fn generate_cargo_toml(config: &IntentConfig) -> String {
    let name = if config.project.name.is_empty() {
        "generated"
    } else {
        &config.project.name
    };

    let version = if config.project.version.is_empty() {
        "0.1.0"
    } else {
        &config.project.version
    };

    let edition = &config.generation.rust_edition;

    format!(
        r#"# @generated by intent-engine v1.0
# DO NOT EDIT — changes will be overwritten

[package]
name = "{name}"
version = "{version}"
edition = "{edition}"

[dependencies]
# Async runtime
tokio = {{ version = "1.35", features = ["full"] }}

# Web framework
axum = {{ version = "0.7", features = ["json"] }}

# Serialization
serde = {{ version = "1.0", features = ["derive"] }}
serde_json = "1.0"

# Error handling
thiserror = "1.0"
anyhow = "1.0"

# Types
uuid = {{ version = "1.6", features = ["v4", "serde"] }}
chrono = {{ version = "0.4", features = ["serde"] }}
rust_decimal = {{ version = "1.33", features = ["serde"] }}

# HTTP client
reqwest = {{ version = "0.11", features = ["json"] }}

# Database
sqlx = {{ version = "0.7", features = ["runtime-tokio", "postgres"] }}

# Logging
tracing = "0.1"
"#
    )
}

/// Generate lib.rs content
pub fn generate_lib_rs(store: &IntentStore) -> String {
    let has_types = !store.types().is_empty();
    let has_endpoints = !store.endpoints().is_empty();
    let has_workflows = !store.workflows().is_empty();

    let mut mods = vec![];

    if has_types {
        mods.push("pub mod types;");
    }
    if has_endpoints {
        mods.push("pub mod endpoints;");
    }
    if has_workflows {
        mods.push("pub mod workflows;");
    }

    mods.push("pub mod effects;");
    mods.push("pub mod errors;");

    let mods_str = mods.join("\n");

    let router_code = if has_endpoints {
        r#"
pub fn app() -> axum::Router {
    endpoints::router()
}
"#
    } else {
        r#"
pub fn app() -> axum::Router {
    axum::Router::new()
}
"#
    };

    format!(
        r#"// @generated by intent-engine v1.0
// DO NOT EDIT — changes will be overwritten

{mods_str}

{router_code}
"#
    )
}

/// Full generation result
#[derive(Debug, Clone, serde::Serialize)]
pub struct GenerationResult {
    pub matches: bool,
    pub files: Vec<GeneratedFile>,
}

#[derive(Debug, Clone, serde::Serialize)]
pub struct GeneratedFile {
    pub path: String,
    pub matches: bool,
    pub reason: String,
}

impl GenerationResult {
    pub fn new() -> Self {
        Self {
            matches: true,
            files: Vec::new(),
        }
    }

    pub fn add_file(&mut self, path: String, content: &str, existing: Option<&str>) {
        let matches = existing.map_or(false, |e| e == content);
        if !matches {
            self.matches = false;
        }

        let reason = if existing.is_none() {
            "new file".to_string()
        } else if matches {
            "unchanged".to_string()
        } else {
            "modified".to_string()
        };

        self.files.push(GeneratedFile {
            path,
            matches,
            reason,
        });
    }
}

impl Default for GenerationResult {
    fn default() -> Self {
        Self::new()
    }
}
